platform :ios, 						'6.0'

xcodeproj 'XBToolkit-ios'
pod 'Underscore.m',					'0.2.1'
pod 'AFNetworking', 				'~> 2.0.3'
pod 'Mantle', 						'~> 1.3.1'
pod 'MantleXMLAdapter', 			:git => 'https://github.com/viteinfinite/MantleXMLAdapter.git'

target 'XBToolkit-iosTests', :exclusive => true do
	pod 'OCMock',						'2.2.1'
  	pod 'GHUnitIOS',					'0.5.8'
end
