platform :osx,						'10.7'
pod 'Underscore.m',					'0.2.0'
pod 'AFNetworking',					'1.1'
pod 'DCKeyValueObjectMapping', 		'1.4'
pod 'OCMock',						'2.0.1'

target 'XBToolkit-osxTests', :exclusive => true do
  pod 'GHUnitOSX',					'0.5.6'
end
