platform :osx,						'10.8'

xcodeproj 'XBToolkit-osx'
pod 'Underscore.m',					'~> 0.2.1'
pod 'AFNetworking', 				'~> 2.4.0'
pod 'Mantle'

target 'XBToolkit-osxTests', :exclusive => true do
	pod 'OCMock',						'2.2.4'
  	pod 'GHUnitOSX',					'0.5.8'
end
